generatorName: cpp-restbed-server
additionalProperties:
  apiPackage: api
  modelPackage: models
  packageName: KnapsackAPI
  packageVersion: 1.0.0
  projectName: knapsack-api
  cppNamespace: knapsack::api
  useStructModel: "true"
  sortParamsByRequiredFlag: "true"
  optionalProjectFile: "true"
  modelNameSuffix: Dto