generatorName: cpp-restsdk
additionalProperties:
  apiPackage: api
  modelPackage: models
  packageName: KnapsackAPI
  packageVersion: 1.0.0
  projectName: knapsack-api
  # Для интеграции с userver можно использовать cpprestsdk в качестве базового
  cppNamespace: knapsack::api
  # Дополнительные настройки
  useStructModel: "true"
  sortParamsByRequiredFlag: "true"
  optionalProjectFile: "true"
  modelNameSuffix: Dto